# whiteboard-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: whiteboard
  template:
    metadata:
      labels:
        app: whiteboard
    spec:
      containers:
      - name: whiteboard
        image: rohitghumare64/whiteboard:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_URL
          value: "${REDIS_URL}"
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_DEBUG
          value: "1"
        - name: FLASK_APP
          value: "app.py"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: whiteboard-service
spec:
  selector:
    app: whiteboard
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
